### ISSUE TITLE
BackupSchedule Datenstruktur

### ISSUE THREAD

**Issue by janritter** [LexicForLXD/Backend#10]
PHP Code der Entity
```
class BackupSchedule
{
    protected $id; //Unique ID
 
    protected $name; //Zur Identifizierung

    protected $description; //Zur Identifizierung (optional)
 
    protected $minute; // (0 bis 59)

    protected $hour; //(0 bis 23)

    protected $day; //(1 bis 31)

    protected $month; //(1 bis 12)

    protected $weekday; // (0 bis 7) 0 und 7 sind beide Sonntag

    protected $destination;

    protected $containers; 
}
```
Die ausgeführten Backups werden in einer eigenen Entität gespeichert

**Comment by janritter** [comment]
@ChibangLW

**Comment by ChibangLW** [comment]
@janritter Da wir ja anacron nutzen wollten, können wir das ganze mit der Ausführungszeit vereinfachen. 
Es muss nur angegeben werden, ob daily, weekly oder monthly ein Backup ausgeführt werden soll. Um den Rest kümmert sich anacron.

**Comment by janritter** [comment]
@ChibangLW Ok, passte ich an
