### ISSUE TITLE
Shell Befehle für Backup

### ISSUE THREAD

**Issue by ChibangLW** [LexicForLXD/Backend#12]
`lxc snapshot <container-name> [<snapshot-name>]` Snapshot Erstellung
`lxc publish <container-name>/<snapshot-name> [--alias name]` Image erstelltung aus Snapshot (liefert fingerprint zurück und ist gleichzeitig Dateiname
`/var/snap/lxd/common/lxd/images` Ort der Images
`duplicity <pfad zum image> <destination>` Eigentliches Backup
`lxc image delete <alias oder fingerprint>` Löscht das Image vom Backup
`lxc delete <container-name>/<snapshot-name>` Löscht den Snapshot vom Backup

**Comment by ChibangLW** [comment]
@janritter

**Comment by janritter** [comment]
Der direkte Zugriff auf den /var/snap/lxd/common/lxd/images Ordner ist nicht möglich (ausser mit root Rechten, sollten wir aber nicht) 

Stattdessen sollten wir das Image als tarball exportieren und diesen später wieder importieren.

### Export command
lxc image export af64621e3813391687ce49416e46e270b744002d11d3c899783bd74731348af9 /home/jan/export/filename 

filename - Name der Datei
Hinweis: der Export Ordner muss vorher vorhanden sein, es kann auch per alias exportiert werden.

### Import command
lxc image import /home/jan/export/filename.tar.gz --alias importedImage

alias ist optional, fingerprint ist der gleiche wie beim export 

### Neuer Container aus dem Snapshot Image
lxc init importedImage NEW-CONTAINER

https://discuss.linuxcontainers.org/t/backup-the-container-and-install-it-on-another-server/463

**Comment by ChibangLW** [comment]
@janritter Okay ändere ich ab.
