### ISSUE TITLE
Befehle Backup wiederherstellen 

### ISSUE THREAD

**Issue by janritter** [LexicForLXD/Backend#14]
Backup Datei in /tmp Ordner entpacken
Image in LXC importieren: 
lxc image import /home/jan/export/filename.tar.gz --alias importedImage

Neuer Container aus dem Snapshot Image: 
lxc init importedImage NEW-CONTAINER

Container aus dem Image erstellen
(Image nach der Erstellung löschen)

**Comment by janritter** [comment]
@ChibangLW

**Comment by ChibangLW** [comment]
Das müsste eigentlich direkt erkannt werden, wenn es in den Ordner kopiert wird. 
Es ist halt die Frage, ob wir dann den originalen Container erst löschen, um dann einen neuen Container aus dem Backup image wieder zu erstellen.

**Comment by janritter** [comment]
@ChibangLW Um komplette configs, wie IP ... zu übernehmen müsste der alte ja zuerst entfernt werden, da einige Optionen ja unique sind, oder?

**Comment by janritter** [comment]
Aktualisierte Befehle:
### Wiederherstellen
#### Duplicity restore in den Ordner /tmp
```
mkdir 13132135746
duplicity restore file:///home/jan/backup/lxd /tmp/13132135746/mein-container.tar.gz 
```
#### LXC Image aus tarball wiederherstellen - Falls Image vorhanden, altes löschen
```
cd 13132135746
lxc image import mein-container.tar.gz --alias mein-container
```
#### Container aus hergestelltem Image erzeugen - Falls vorhanden, vorhandenen Container löschen
```
lxc init mein-container MEIN-CONTAINER
```
#### Lokale restore Daten löschen
```
rm -rf /tmp/13132135746
```
Wiederhergestelltes Image löschen oder in Lexic einbinden

**Comment by janritter** [comment]
### Einzelnen Container wiederherstellen
```
duplicity restore --no-encryption file:///home/jan/backup/lxd/backup144 --file-to-restore TestContainer.tar.gz /tmp/export123/TestContainer.tar.gz
```
