### ISSUE TITLE
Objekt der Assoziation enthält nur die ID 

### ISSUE THREAD

**Issue by janritter** [LexicForLXD/Backend#22]
Wenn man in einem PHPUnit Test die Funktion getBackupSchedule auf der Backup Entity ausführt erhält man nur das unten gezeigte Objekt (also nur id gesetzt), dabei sind in der Datenbank alle Werte gesetzt. 

Liegt das Problem im Test oder bei der Assoziation?

```
OK (1 test, 3 assertions)
BackupControllerTest.php on line 223:
Proxies\__CG__\AppBundle\Entity\BackupSchedule {#1922
  +__isInitialized__: false
  #id: 14
  #name: null
  #description: null
  #executionTime: null
  #destination: null
  #type: null
  #token: null
  #containers: null
  #backups: null
   …2
}
```

Es sieht so aus, als würde das Problem in der PHPunit bridge liegen

**Comment by janritter** [comment]
@ChibangLW

**Comment by ChibangLW** [comment]
@janritter still valid?

**Comment by janritter** [comment]
@ChibangLW I didn't tried newer versions, maybe the problem is fixed now
