### ISSUE TITLE
Duplicity commands

### ISSUE THREAD

**Issue by janritter** [LexicForLXD/Backend#24]
### Create local full Backup - Passphrase required
```
duplicity full /home/jan/go file:///home/jan/backup      
```
### Create local incremental Backup - Passphrase required
```
duplicity incremental /home/jan/go file:///home/jan/backup  
```
### Get list of Backups
```
duplicity collection-status file:///home/jan/backup   
```
### Restore Backup (incremental or full) for a specific timestamp - Passphrase required
```
duplicity restore file:///home/jan/backup --time 2018-03-11T18:30:33 /home/jan/test/test 
```
Duplicity searches for the closest matching date and restores this Backup

**Comment by janritter** [comment]
@ChibangLW

**Comment by ChibangLW** [comment]
Man kann auch auf full und incremental verzichten, dann wird beim ersten mal ein full und im Anschluss incrementell ausgeführt.
