### ISSUE TITLE
Can't find what "lexic" is via google so what is it or what does it do?

### ISSUE THREAD

**Issue by bmullan** [LexicForLXD/Backend#247]
Sorry for being dumb but what is Lexic and what does it do ?

I tried a google search and only came up with perhaps its some kind of game.

**Comment by ChibangLW** [comment]
Lexic is a container management system for lxc. It can connect to multiple lxc host and manage these. 
The backend interacts directly with lxc and the frontend connects to the backend.

**Comment by bmullan** [comment]
@ChibangLW 

Thanks... just a recommendation but you might add that short explanation the the top of your README so people like myself that find LEXIC know what it's purpose is.
