### ISSUE TITLE
Berechtigungsfehler - Backups

### ISSUE THREAD

**Issue by janritter** [LexicForLXD/Backend#39]
### Problem
Alle backups/ endpoints mit Methode POST scheinen ohne OAuth2 erreichbar zu sein.
Beispiel : {{url}}/backups/schedules

### Soll
Nur der Webhook endpoint sollte ohne OAuth2 erreichbar sein

**Comment by ChibangLW** [comment]
Wir könnten es sonst auf {{url}} /webhook/backups ändern.

**Comment by janritter** [comment]
Guter Plan, ich erstelle einen neuen Branch

**Comment by janritter** [comment]
@ChibangLW Ist angepasst {{url}}/webhooks/backups , der Branch ist fix/issue-39-webhook.
Kannst du dann noch die Anpassungen an der Skript generierung machen

**Comment by ChibangLW** [comment]
@janritter Ich muss da eigentlich nichts anpassen, da ich das dynamisch mit dem namen der Route mache.
