### ISSUE TITLE
Backuperstellung (manuell)

### ISSUE THREAD

**Issue by ChibangLW** [LexicForLXD/Backend#4]
**Was wird gefordert:**
*  Ziel kann ausgewählt werden
*  Container kann ausgewählt werden
*  Host kann ausgewählt werden (alle Container dieses Hosts)

**Schritte für mehrere Container:**
1.  Manuelles Backup auswählen
2.  Mehrere Container anklicken / Einen Host auswählen
3.  Remote Destination auswählen
4.  Request abschicken

**Schritte für einen Container:** (wie oben nur mit einem Host oder)
1.  Übersicht des Containers aufrufen
2.  Backup erstellen auswählen
3.  Remote Destination auswählen
4.  Request abschicken

**Daten die übergeben werden:**
*  containerIds (Array)
*  remoteDestId

**Endpoint**
*  `/hosts/{hostId}/backups` alle Container / nur ausgewählte Container wenn Array nicht leer werden gebackupt 
*  `/containers/{containerId}/backups` ein Container wird gebackupt

**Comment by janritter** [comment]
Sieht sehr gut aus, die Frage ist noch wie wir die Endpoints für Backup erstellen und wiederherstellen unterscheiden, also wie beim wiederherstellen die pfade aussehen.

- `/hosts/{hostId}/backups/create` - Zum erstellen 
- `/hosts/{hostId}/backups` - Alle Backups für den Host auflisten
- `/hosts/{hostId/backups/{backupId}/restore` - Wiederherstellen von einem speziellen Backup

**Comment by ChibangLW** [comment]
@janritter Wie wäre es wenn wir dann `/hosts/{hostid}/recovery/{backupId}` benutzen?
