### ISSUE TITLE
Backuperstellung (automatisiert)

### ISSUE THREAD

**Issue by ChibangLW** [LexicForLXD/Backend#5]
**Was wird gefordert** 
- Ziel kann ausgewählt werden
- Container oder kompletter Host kann ausgewählt werden
- Zeitplan kann erstellt werden (Syntax ähnlich zu cronjob) 
- Alles soll geändert werden können

**Schritte für mehrere Container:**
1.  Manuelles Backup auswählen
2.  Mehrere Container anklicken / Einen Host auswählen
3.  Remote Destination auswählen
4.  Zeitplan eintragen
5.  Request abschicken

**Schritte für einen Container:** (wie oben nur mit einem Host oder)
1.  Übersicht des Containers aufrufen
2.  Backup erstellen auswählen
3.  Remote Destination auswählen
4.  Zeitplan eintragen
5.  Request abschicken

**Datenstruktur**
```js
{
  "timetable": {
    "minute": 1, // (0 bis 59)
    "hour": 1, //(0 bis 23)
    "day": 1, //(1 bis 31)
    "month": 1, //(1 bis 12)
    "weekday": 1 // (0 bis 7) 0 und 7 sind beide Sonntag
  },
  "destination": ???, // Wie sollen wir hier vorgehen? id (also in DB gespeichert) oder einfach Ziel wie es duplicity erwartet?
  "containers": [1,2,3]  // oder "host": 1
}
```

**Sonstige Notizen**
- Man kann auch anacron anstatt crontab benutzen. Hat den Vorteil, dass das script auch ausgeführt wird, wenn der Server mal zum gewollten Zeitpunkt nicht läuft.
- Wir müssen bedenken, dass beim Löschen des Containers dann auch der Crontab gelöscht wird.

**Comment by ChibangLW** [comment]
@janritter

**Comment by janritter** [comment]
Ich würde das Ziel wie in Duplicity als direkte Adresse speichern

**Comment by ChibangLW** [comment]
# UPDATE

- Es wird jetzt anacron benutzt, folglich muss nur noch hourly, daily, weekly oder monthly gesetzt werden.
- Destination ist nun eine eigene Entity und es wird mit der Assoziation gearbeitet.
