### ISSUE TITLE
Backup script

### ISSUE THREAD

**Issue by ChibangLW** [LexicForLXD/Backend#74]
### Inkrementelles Backup
Wenn incremental im Backup command vorhanden ist, vorher aber nie ein full Backup erstellt wurde, wird das Backup fehlschlagen.
### Backup Destination
Wenn man z.B. rsync als Protokoll nutzt muss der Zielordner inklusive Subordner für den BackupSchedule bereits vorhanden sein. 
Vielleicht gibt es ein flag, damit der Subordner automatisch erstellt wird.

**Comment by ChibangLW** [comment]
@janritter hast du die beiden Sachen ausprobiert?

**Comment by janritter** [comment]
@ChibangLW Ich habe das zu dem Zeitpunkt wo ich das Ticket erstellt habe getestet. Ich vermute das Ordner Problem ist nicht nur bei rsync vorhanden.

**Comment by ChibangLW** [comment]
@janritter Sollte dann bei incrementell eventuell das flag weggelassen werden? Weil duplicity machte dann standardmäßig erst ein full und dann incremental.

**Comment by janritter** [comment]
@ChibangLW Wäre eine gute Lösung, das inkrementelle Verhalten ist ja dann identisch.
